# -*- coding: utf-8 -*-
"""API_Twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7Yq-PsZ2Lm7soKPTSN8ZFLtvg2zZLIO
"""

import requests
import pandas as pd
import json
import re

import requests
#Conectarse con la API de rapidapi

url = "https://twitter154.p.rapidapi.com/user/tweets"

payload = {
    "username": "heybanco",
    "user_id": "930934081466060800",
    "include_replies": False,
    "include_pinned": False,
    "limit": 10  # Define el número máximo de tweets que deseas obtener
}
headers = {
    "content-type": "application/json",
    "X-RapidAPI-Key": "ddefea3ab4msh30c08b580fbc3eap170eedjsn36ddd882c7e0",
    "X-RapidAPI-Host": "twitter154.p.rapidapi.com"
}

response = requests.post(url, json=payload, headers=headers)

print(response.json())

#Se encontró una restricción en cuanto al plan gratuito de la API, ya que solo permite analizar cierto número de teets

#Con base en la información obtenida se hace una limpieza de datos y una tabla con los tweets id y el nombre de usuario al que se le respindió
json_response = response.json()
print(json_response)
tweet_data = []
for result in json_response["results"]:
    tweet_id = result["tweet_id"]
    text = result["text"]
    usernames_mentioned = re.findall(r'@(\w+)', text)  # Buscar las menciones (@username) en el texto del tweet
    for username in usernames_mentioned:
        tweet_data.append({"tweet_id": tweet_id, "username": username})

# Crear un DataFrame con los datos extraídos
df_mentions = pd.DataFrame(tweet_data)

df_mentions #Se muestra la tabla

#Con base en los tweets id se buscan los detalles del tweet para encontrar el comentario original y poder analizarlo posteriormente como parte de la base de datos
import requests

url = "https://twitter154.p.rapidapi.com/tweet/details"

querystring = {"tweet_id":"1786528850245218434"}

headers = {
	"X-RapidAPI-Key": "ddefea3ab4msh30c08b580fbc3eap170eedjsn36ddd882c7e0",
	"X-RapidAPI-Host": "twitter154.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

#Se obtiene el Conversation id

#Ya con el conversation id se obtiene el comentario original
import requests

url = "https://twitter154.p.rapidapi.com/tweet/details"

querystring = {"tweet_id":"1786528008565575924"} #Poner el conversation_id

headers = {
	"X-RapidAPI-Key": "ddefea3ab4msh30c08b580fbc3eap170eedjsn36ddd882c7e0",
	"X-RapidAPI-Host": "twitter154.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())